#!/usr/bin/with-contenv bash

DAEMON_ARGS="$URL $STARTTLS $BASEDN $BINDDN $BINDPW $FILTER"
DAEMON_ARGS="$DAEMON_ARGS $COOKIENAME $HEADERNAME $MFA"

exec s6-setuidgid abc python3 /app/nginx-ldap-auth-daemon.py --host 0.0.0.0 --port 8888 $DAEMON_ARGS