#!/usr/bin/with-contenv bash

# generate fernet key for ldap if it doesn't exist
if grep -q 'REPLACEWITHFERNETKEY' /app/ldap-backend-app.py; then
    FERNETKEY=$(python3 /app/fernet-key.py)
    sed -i "s/REPLACEWITHFERNETKEY/${FERNETKEY}/" /app/ldap-backend-app.py
    sed -i "s/REPLACEWITHFERNETKEY/${FERNETKEY}/" /app/nginx-ldap-auth-daemon.py
    echo "generated fernet key"
fi

# Set Duo Parameters
if [ -n "$DUO_IKEY" ]  && grep -q 'REPLACEWITHDUOIKEY' /app/ldap-backend-app.py; then
    sed -i "s/REPLACEWITHDUOIKEY/${DUO_IKEY}/" /app/ldap-backend-app.py
    echo "set Duo ikey"
fi
if [ -n "$DUO_SKEY" ]  && grep -q 'REPLACEWITHDUOSKEY' /app/ldap-backend-app.py; then
    sed -i "s/REPLACEWITHDUOSKEY/${DUO_SKEY}/" /app/ldap-backend-app.py
    echo "set Duo skey"
fi
if [ -n "$DUO_AKEY" ]  && grep -q 'REPLACEWITHDUOAKEY' /app/ldap-backend-app.py; then
    sed -i "s/REPLACEWITHDUOAKEY/${DUO_AKEY}/" /app/ldap-backend-app.py
    echo "set Duo akey"
fi
if [ -n "$DUO_HOST" ]  && grep -q 'REPLACEWITHDUOHOST' /app/ldap-backend-app.py; then
    sed -i "s/REPLACEWITHDUOHOST/${DUO_HOST}/" /app/ldap-backend-app.py
    echo "set Duo host"
fi